[package]
name = "gtk-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
bt-backend = { path = "../bt-backend"}